### ISSUE TITLE
formatting for html view

### ISSUE THREAD

**Issue by drmperez** [nwchemgit/nwchem-wiki#21]
Text is center aligned after 1st table in GRID section in the file: Density-Functional-Theory-for-Molecules.md

I believe you need a blank line between the table and  '</center>' so that the following text is left-aligned in the html view.

<img width="746" alt="Screen Shot 2020-07-27 at 2 41 40 PM" src="https://user-images.githubusercontent.com/6635366/88590244-9b817800-d017-11ea-9197-80c523f6cff6.png">

**Comment by edoapra** [comment]
@drmperez Thanks for the feedback. The website should now contain the fix
