### ISSUE TITLE
PDF User Manual download

### ISSUE THREAD

**Issue by Ray-wzl** [nwchemgit/nwchem-wiki#23]
Dear fellows:
     I want to have calculations with NWChem. So, a pdf user manual is needed. However, when I have a check on the NWChem wiki  or official website, only fond that "A PDF version of the Documentation pages is available (OBSOLETE)". So, can anyone tell me where to download or sent me a PDF version of  NWChem at [201920282@mail.sdu.edu.cn.](url) . Much appreciate.

**Comment by edoapra** [comment]
Unfortunately, we cannot provide a PDF version of the users manual at this point in time.
The NWChem website https://nwchemgit.github.io is the best reference we can provide

**Comment by edoapra** [comment]
A PDF version of the manual is now available at
https://nwchemgit.github.io/PDF.html
