### ISSUE TITLE
Installation instructions unclear (WSL)

### ISSUE THREAD

**Issue by Dries1998** [nwchemgit/nwchem-wiki#24]
Hi, it is my first time using WSL and NWChem. After I install WSL according to the instructions linked in the guide and installing NWChem using sudo apt install nwchem. I am confused what instructions I should follow next. Do i need to do any of the things listed under "Compiling from source" or do I immediately start with setting up binaries and such? Or is it already done after entering the command I mentioned earlier? Any help is appreciated.

**Comment by edoapra** [comment]
After
```
sudo apt install nwchem
```
NWChem is ready to go. You can read the following page for instructions on how to run NWCHem
https://nwchemgit.github.io/Running.html#parallel-execution-on-unix-based-parallel-machines-including-workstation-clusters-using-mpi
