### ISSUE TITLE
`c240_631gs`: Facing issues with ao no basis 

### ISSUE THREAD

**Issue by lalith-mcw** [nwchemgit/nwchem-wiki#28]
Copied the library file contents to the nw file itself, still having this error while running nwchem with this config file (c240_631gs.nw)
![image](https://user-images.githubusercontent.com/84698958/194811498-c2d53918-4519-4c15-b296-56db67c08d22.png)

Error statement:
![image](https://user-images.githubusercontent.com/84698958/194811726-9e18f002-7a09-4ba4-8793-02f47a900024.png)

Where do I find the ao basis for carbon ? Couldn't find the same in basis/libraries/

**Comment by edoapra** [comment]
Please post this problem to   
https://github.com/nwchemgit/nwchem/issues/new?assignees=&labels=&template=bug_report.md&title=   
 by attaching the complete input and output files
