### ISSUE TITLE
typo in the ECP chapter

### ISSUE THREAD

**Issue by fishjojo** [nwchemgit/nwchem-wiki#32]
In this sentence
```
The $n_{lk}$ exponent is shifted by 2, in accordance with most of the ECP literature and implementations, i.e., $n_{lk}$ implies $r^2$.
```
$n_{lk}=?$ implies $r^2$

**Comment by edoapra** [comment]
Thank you very much for spotting this issue.
The wiki mark-down  source  the website html output have been updated
